- type: job
  parent: CMJobSquadBase
  id: CMSOFEngispecPVE
  name: rmc-job-name-marine-raider-engispec-PVE
  description: cm-job-description-combat-tech
  playTimeTracker: CMJobSOFEngispecPVE
  startingGear: RMCGearSOFEngispec
  dummyStartingGear: RMCGearMarineRaider
  icon: CMJobIconSOFEngineer
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  ranks:
    RMCRankGunnerySergeant: []
  accessGroups:
  - MARSOCEngispecAccessPVE
  - ShipMasterAccess
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: Skills
      skills:
        RMCSkillEndurance: 5
        RMCSkillEngineer: 5
        RMCSkillConstruction: 6
        RMCSkillPilot: 1
        RMCSkillPowerLoader: 1
        RMCSkillVehicles: 2
        RMCSkillFireman: 3
        RMCSkillSpecialistWeapons: 7
        RMCSkillFirearms: 2
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillMeleeWeapons: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: cm-job-prefix-SOF-engispec
    - type: TacticalMapIcon
      icon:
        sprite: _RNMC14/Interface/map_blips.rsi
        state: sof_engineer
    - type: Sleeping

- type: playTimeTracker
  id: CMJobSOFEngispecPVE
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointEngispecSOF
  name: SOF Engineering specialist spawn point
  components:
  - type: SpawnPoint
    job_id: CMSOFEngispecPVE
  - type: Sprite
    state: marine_spawn

- type: entity
  parent: CMIDCardStandardDogtag
  id: CMDogtagSOFEngispec
  name: SOF Engiical Specialist's dogtags
  components:
  - type: PresetIdCard
    job: CMSOFEngispecPVE

- type: startingGear
  id: RMCGearSOFEngispec
  equipment:
    id: CMDogtagSOFEngispec
